// <auto-generated />
using System;
using BibliotekaMultimediow;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BibliotekaMultimediow.Migrations
{
    [DbContext(typeof(BazaDanych))]
    [Migration("20200503131731_MigrationV5")]
    partial class MigrationV5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("BibliotekaMultimediow.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyUlubione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ocena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Rok")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("nieznany");

                    b.Property<int>("WykonawcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("AlbumId");

                    b.ToTable("Albumy");

                    b.HasData(
                        new
                        {
                            AlbumId = 1,
                            CzyUlubione = false,
                            Nazwa = "nieznany",
                            Ocena = 0,
                            Rok = "nieznany",
                            WykonawcaId = 1
                        });
                });

            modelBuilder.Entity("BibliotekaMultimediow.Utwor", b =>
                {
                    b.Property<int>("UtworId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<bool>("CzyUlubione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ocena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Rok")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("nieznany");

                    b.Property<string>("UrlPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("WykonawcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("UtworId");

                    b.ToTable("Utwory");
                });

            modelBuilder.Entity("BibliotekaMultimediow.Wykonawca", b =>
                {
                    b.Property<int>("WykonawcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyUlubione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ocena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("WykonawcaId");

                    b.ToTable("Wykonawcy");

                    b.HasData(
                        new
                        {
                            WykonawcaId = 1,
                            CzyUlubione = false,
                            Nazwa = "nieznany",
                            Ocena = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
