// <auto-generated />
using System;
using BibliotekaMultimediow;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BibliotekaMultimediow.Migrations
{
    [DbContext(typeof(BazaDanych))]
    partial class BazaDanychModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("BibliotekaMultimediow.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyUlubione")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ocena")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rok")
                        .HasColumnType("TEXT");

                    b.Property<int>("WykonawcaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlbumId");

                    b.ToTable("Albumy");
                });

            modelBuilder.Entity("BibliotekaMultimediow.Utwor", b =>
                {
                    b.Property<int>("UtworId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyUlubione")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ocena")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rok")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("WykonawcaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UtworId");

                    b.ToTable("Utwory");
                });

            modelBuilder.Entity("BibliotekaMultimediow.Wykonawca", b =>
                {
                    b.Property<int>("WykonawcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyUlubione")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ocena")
                        .HasColumnType("INTEGER");

                    b.HasKey("WykonawcaId");

                    b.ToTable("Wykonawcy");
                });
#pragma warning restore 612, 618
        }
    }
}
